version: 2

project_name: minio-operator

release:
  name_template: "Version {{.Version}}"

builds:
  - id: minio-operator
    main: ./cmd/operator/
    dir: .
    binary: minio-operator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/minio/operator/pkg.ReleaseTag={{.Tag}} -X github.com/minio/operator/pkg.CommitID={{.FullCommit}} -X github.com/minio/operator/pkg.Version={{.Version}} -X github.com/minio/operator/pkg.ShortCommitID={{.ShortCommit}} -X github.com/minio/operator/pkg.ReleaseTime={{.Date}}
    flags:
      - -trimpath

  - id: minio-operator-sidecar
    main: ./cmd/sidecar/
    dir: sidecar
    binary: minio-operator-sidecar
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/minio/operator/sidecar/pkg.ReleaseTag={{.Tag}} -X github.com/minio/operator/sidecar/pkg.CommitID={{.FullCommit}} -X github.com/minio/operator/sidecar/pkg.Version={{.Version}} -X github.com/minio/operator/sidecar/pkg.ShortCommitID={{.ShortCommit}} -X github.com/minio/operator/sidecar/pkg.ReleaseTime={{.Date}}
    flags:
      - -trimpath

archives:
  - id: minio-operator
    ids:
      - minio-operator
    formats:
      - binary
    name_template: "minio-operator_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

  - id: minio-operator-sidecar
    ids:
      - minio-operator-sidecar
    formats:
      - binary
    name_template: "minio-operator-sidecar_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Tag }}-next"

changelog:
  use: git
  sort: asc

dockers_v2:
  - id: minio-operator
    ids:
      - minio-operator
    images:
      - ghcr.io/gitgrave/minio-operator
    tags:
      - "{{ .Tag }}"
      - latest
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - LICENSE
      - CREDITS
    build_args:
      TAG: "{{ .Tag }}"
    labels: &labels
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "https://github.com/gitgrave/operator"
      "org.opencontainers.image.licenses": "AGPL-3.0"

  - id: minio-operator-sidecar
    ids:
      - minio-operator-sidecar
    images:
      - ghcr.io/gitgrave/minio-operator-sidecar
    tags:
      - "{{ .Tag }}"
      - latest
    dockerfile: sidecar/Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - LICENSE
      - sidecar/CREDITS
    build_args:
      TAG: "{{ .Tag }}"
    labels: *labels
